# find_path(FUZZY_INCLUDE_DIR fuzzy.h)
# find_library(FUZZY_LIBRARY NAMES fuzzy)
# include(FindPackageHandleStandardArgs)
# find_package_handle_standard_args(Fuzzy DEFAULT_MSG FUZZY_LIBRARY FUZZY_INCLUDE_DIR)
# if(FUZZY_FOUND)
#   set(FUZZY_INCLUDE_DIRS ${FUZZY_INCLUDE_DIR})
#   set(FUZZY_LIBRARIES ${FUZZY_LIBRARY})
#   mark_as_advanced(FUZZY_INCLUDE_DIR FUZZY_LIBRARY)
# endif(FUZZY_FOUND)